"""Initial schema

Revision ID: 08b2baeb9c50
Revises: 
Create Date: 2025-11-15 12:24:57.382529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08b2baeb9c50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_schools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('price_candles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_symbol', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('current_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_symbol', sa.String(length=10), nullable=False),
    sa.Column('horizon', sa.Enum('SHORT', 'MEDIUM', 'LONG', 'OVERALL', name='horizon'), nullable=False),
    sa.Column('finance_school_id', sa.UUID(), nullable=True),
    sa.Column('weighted_score_buy', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('weighted_score_neutral', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('weighted_score_sell', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('final_label', sa.Enum('BUY', 'NEUTRAL', 'SELL', name='direction'), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['finance_school_id'], ['finance_schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('influencers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('handle', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('finance_school_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['finance_school_id'], ['finance_schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('handle')
    )
    op.create_table('trust_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('influencer_id', sa.UUID(), nullable=False),
    sa.Column('asset_symbol', sa.String(length=10), nullable=True),
    sa.Column('horizon', sa.Enum('SHORT', 'MEDIUM', 'LONG', 'OVERALL', name='horizon'), nullable=False),
    sa.Column('score', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('window_end', sa.DateTime(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tweets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('influencer_id', sa.UUID(), nullable=False),
    sa.Column('tweet_id', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('tweeted_at', sa.DateTime(), nullable=False),
    sa.Column('asset_symbols', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('processed_for_sentiment', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tweet_id')
    )
    op.create_table('sentiment_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tweet_id', sa.UUID(), nullable=False),
    sa.Column('asset_symbol', sa.String(length=10), nullable=False),
    sa.Column('direction', sa.Enum('BUY', 'NEUTRAL', 'SELL', name='direction'), nullable=False),
    sa.Column('horizon', sa.Enum('SHORT', 'MEDIUM', 'LONG', 'OVERALL', name='horizon'), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('matures_at', sa.DateTime(), nullable=False),
    sa.Column('evaluated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction_outcomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sentiment_prediction_id', sa.UUID(), nullable=False),
    sa.Column('asset_symbol', sa.String(length=10), nullable=False),
    sa.Column('horizon', sa.Enum('SHORT', 'MEDIUM', 'LONG', 'OVERALL', name='horizon'), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('return_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('outcome', sa.Enum('CORRECT', 'WRONG', 'UNCLEAR', name='outcome'), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.Column('evaluation_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sentiment_prediction_id'], ['sentiment_predictions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sentiment_prediction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction_outcomes')
    op.drop_table('sentiment_predictions')
    op.drop_table('tweets')
    op.drop_table('trust_scores')
    op.drop_table('influencers')
    op.drop_table('current_signals')
    op.drop_table('price_candles')
    op.drop_table('finance_schools')
    # ### end Alembic commands ###

